[project]
name = "crawl-practice-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "drissionpage>=4.1.0.17",
    "pandas>=2.2.3",
    "pyecharts>=2.0.8",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
